# Generated by Django 2.1 on 2018-08-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wechat_id', models.CharField(max_length=255)),
                ('icon_path', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.IntegerField()),
                ('createtime', models.DateTimeField(blank=True, null=True)),
                ('updatetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'apps_user',
                'managed': True,
            },
        ),
    ]
